# Copyright (c) 2023-present, Royal Bank of Canada.
# Copyright (c) 2022, Tung Nguyen
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.
#####################################################################################
# Code is based on the TNP (https://arxiv.org/abs/2201.12740) implementation
# from https://github.com/tung-nd/TNP-pytorch by Tung Nguyen 
####################################################################################


num_latents: 8
dim_x: 2
dim_y: 5
d_model: 16
emb_depth: 3
dim_feedforward: 64
nhead: 1
dropout: 0.5
num_layers: 4
drop_y: 0.0
cov_approx: 'lowrank' # cholesky or lowrank parameterization
prj_dim: 20
prj_depth: 4
diag_depth: 4 # only for lowrank parameterization option
